### ISSUE TITLE
Wireframes for Request Access - DRAFT 01

### ISSUE THREAD

**Issue by MPM9000** [gctools-outilsgc/concierge#30]
Shown is a 2 step process that could occur after the system rejects the email address because it is not on the whitelist. Notes and suggestions have been added to the images but by no means are to be considered final.

**Comment by MPM9000** [comment]
![000_new_registration_request_access_bad_email](https://user-images.githubusercontent.com/36711228/37847566-97e4a74e-2ea7-11e8-9f3a-3076326a49fd.jpg)
![001_new_registration_request_access_step01](https://user-images.githubusercontent.com/36711228/37847567-98434560-2ea7-11e8-889e-5d4582ee8e2f.jpg)
![002_new_registration_request_access_step02](https://user-images.githubusercontent.com/36711228/37847568-98542a74-2ea7-11e8-9da3-75ba6f3ab454.jpg)
![003_new_registration_request_access_step03](https://user-images.githubusercontent.com/36711228/37847569-98625126-2ea7-11e8-89d7-ca0d5e444711.jpg)

**Comment by MPM9000** [comment]
Updates made to the instructional text and button text. Removed global link to help desk.

![000_new_registration_request_access_bad_email](https://user-images.githubusercontent.com/36711228/37905534-3114c5da-30cd-11e8-94e2-8143e9b3dd5f.jpg)
![001_new_registration_request_access_step01](https://user-images.githubusercontent.com/36711228/37905535-3123dbe2-30cd-11e8-8fac-fbe14d259a33.jpg)
![002_new_registration_request_access_step02](https://user-images.githubusercontent.com/36711228/37905537-31326a72-30cd-11e8-8ae1-7435accee26f.jpg)
![003_new_registration_request_access_step03](https://user-images.githubusercontent.com/36711228/37905538-31407f72-30cd-11e8-81ea-156992a27625.jpg)

**Comment by beckyjeong** [comment]
![](https://user-images.githubusercontent.com/36711228/37905534-3114c5da-30cd-11e8-94e2-8143e9b3dd5f.jpg)

It's great that we have the '?' info button on the second wireframe - it may be better to have it from the get-go, so that the user does not have to "guess" the format. It will also be good to give an example (i.e., John Doe) as some users may include their middle name as it appears on their government issued IDs. _*refer to the comment for the second screen_

Same goes for the '?' info button for Email with an example. _*refer to the comment for the second screen_

Error message - should talk to @LemieuxGen Marianne and the Outreach team for the wording. Something along the lines of: "Sorry, you are not able to use that email address for your account. If applicable, please use another email address provided to you by your institution, organization or business (i.e., John.Doe@canada.ca)."

![](https://user-images.githubusercontent.com/36711228/37905535-3123dbe2-30cd-11e8-8fac-fbe14d259a33.jpg)

"Please provide your first and last name **only**, as they appear on your **government issued IDs** (i.e., **John Doe**)."

"Please use the email **address** provided to you by your institution, organization or business, if applicable **(i.e., John.Doe@canada.ca)**."

Address of Residence - dropdown list (suggestions) for 'City', 'Province/State' and 'Country' will make it a much smoother process for users (spelling mistakes, format, etc.). Note that 'City' and 'Country' should still accept open text in case we miss certain countries/areas. We should stick to one format of postal code (A1B 2C3 or A1B2C3), so that when user enters in their code, it automatically pushes for one format.

![](https://user-images.githubusercontent.com/36711228/37905537-31326a72-30cd-11e8-8ae1-7435accee26f.jpg)

How did you hear about GC Collab --> GCcollab one word; Do we want to make it easier for users to choose from a pre-identified list (e.g., from colleague) and allow for open text only when they choose 'other'?

What is your occupation? - '?' info button with something along the lines of "Please identify your main/primary occupation"

What is the website URL of the **institution**? - What is the dropdown for?

Password and Confirm password - We need another '?' info button for the valid email address rules - e.g. Microsoft Exchange"

"Use only alphanumeric characters. That is, use only “A” through “Z” and “0 (zero)” through “9”.
Do not use the following characters: < > ( ) [ ] ; : , @ \
As long as they are not the first character in the e-mail address, hyphens ( – ), underscores ( _ ), periods ( . ), and numeric characters (“0” through “9”) are acceptable characters to use within the address."

Also need a password validation error message: "Passwords do not match. Please confirm your password."

**Comment by beckyjeong** [comment]
#40 
#43

**Comment by LemieuxGen** [comment]
Closing to avoid having multiple issues on the Registration and requesting membership task.
